/*******************************************************************************
 * Copyright (c) 2017 Intuit
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.06 at 02:08:21 PM PDT 
//


package com.intuit.ipp.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentStatusEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PaymentStatusEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Draft"/>
 *     &lt;enumeration value="Overdue"/>
 *     &lt;enumeration value="Pending"/>
 *     &lt;enumeration value="Payable"/>
 *     &lt;enumeration value="Paid"/>
 *     &lt;enumeration value="Trash"/>
 *     &lt;enumeration value="UnPaid"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PaymentStatusEnum")
@XmlEnum
public enum PaymentStatusEnum {

    @XmlEnumValue("Draft")
    DRAFT("Draft"),
    @XmlEnumValue("Overdue")
    OVERDUE("Overdue"),
    @XmlEnumValue("Pending")
    PENDING("Pending"),
    @XmlEnumValue("Payable")
    PAYABLE("Payable"),
    @XmlEnumValue("Paid")
    PAID("Paid"),
    @XmlEnumValue("Trash")
    TRASH("Trash"),
    @XmlEnumValue("UnPaid")
    UN_PAID("UnPaid");
    private final String value;

    PaymentStatusEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PaymentStatusEnum fromValue(String v) {
        for (PaymentStatusEnum c: PaymentStatusEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
