//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.18 at 04:20:25 PM IST 
//


package com.intuit.ipp.data;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PerItemAdjustEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="PerItemAdjustEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Cost"/&gt;
 *     &lt;enumeration value="CurrentCustomPrice"/&gt;
 *     &lt;enumeration value="StandardPrice"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PerItemAdjustEnum")
@XmlEnum
public enum PerItemAdjustEnum {

    @XmlEnumValue("Cost")
    COST("Cost"),
    @XmlEnumValue("CurrentCustomPrice")
    CURRENT_CUSTOM_PRICE("CurrentCustomPrice"),
    @XmlEnumValue("StandardPrice")
    STANDARD_PRICE("StandardPrice");
    private final String value;

    PerItemAdjustEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PerItemAdjustEnum fromValue(String v) {
        for (PerItemAdjustEnum c: PerItemAdjustEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
