//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.23 at 02:36:16 PM PDT 
//


package com.intuit.ipp.data;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals2;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy2;
import org.jvnet.jaxb2_commons.lang.HashCode2;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy2;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * Defines Sales Form Prefs details 
 * 
 * <p>Java class for SalesFormsPrefs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SalesFormsPrefs">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UsingProgressInvoicing" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="CustomField" type="{http://schema.intuit.com/finance/v3}CustomFieldDefinition" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CustomTxnNumbers" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="DelayedCharges" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="SalesEmailCc" type="{http://schema.intuit.com/finance/v3}EmailAddress" minOccurs="0"/>
 *         &lt;element name="SalesEmailBcc" type="{http://schema.intuit.com/finance/v3}EmailAddress" minOccurs="0"/>
 *         &lt;element name="EmailCopyToCompany" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="AllowDeposit" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="AllowDiscount" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="DefaultDiscountAccount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AllowEstimates" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="EstimateMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ETransactionEnabledStatus" type="{http://schema.intuit.com/finance/v3}ETransactionEnabledStatusEnum" minOccurs="0"/>
 *         &lt;element name="ETransactionAttachPDF" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ETransactionPaymentEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IPNSupportEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="InvoiceMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AllowServiceDate" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="AllowShipping" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="DefaultShippingAccount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DefaultItem" type="{http://schema.intuit.com/finance/v3}ReferenceType" minOccurs="0"/>
 *         &lt;element name="DefaultTerms" type="{http://schema.intuit.com/finance/v3}ReferenceType" minOccurs="0"/>
 *         &lt;element name="DefaultDeliveryMethod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AutoApplyCredit" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="AutoApplyPayments" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="PrintItemWithZeroAmount" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="DefaultShipMethodRef" type="{http://schema.intuit.com/finance/v3}ReferenceType" minOccurs="0"/>
 *         &lt;element name="DefaultMarkup" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="TrackReimbursableExpensesAsIncome" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="UsingSalesOrders" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="UsingPriceLevels" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="DefaultFOB" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DefaultCustomerMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SalesFormsPrefs", propOrder = {
    "usingProgressInvoicing",
    "customField",
    "customTxnNumbers",
    "delayedCharges",
    "salesEmailCc",
    "salesEmailBcc",
    "emailCopyToCompany",
    "allowDeposit",
    "allowDiscount",
    "defaultDiscountAccount",
    "allowEstimates",
    "estimateMessage",
    "eTransactionEnabledStatus",
    "eTransactionAttachPDF",
    "eTransactionPaymentEnabled",
    "ipnSupportEnabled",
    "invoiceMessage",
    "allowServiceDate",
    "allowShipping",
    "defaultShippingAccount",
    "defaultItem",
    "defaultTerms",
    "defaultDeliveryMethod",
    "autoApplyCredit",
    "autoApplyPayments",
    "printItemWithZeroAmount",
    "defaultShipMethodRef",
    "defaultMarkup",
    "trackReimbursableExpensesAsIncome",
    "usingSalesOrders",
    "usingPriceLevels",
    "defaultFOB",
    "defaultCustomerMessage"
})
public class SalesFormsPrefs implements Serializable, Equals2, HashCode2
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "UsingProgressInvoicing")
    protected Boolean usingProgressInvoicing;
    @XmlElement(name = "CustomField")
    protected List<CustomFieldDefinition> customField;
    @XmlElement(name = "CustomTxnNumbers")
    protected Boolean customTxnNumbers;
    @XmlElement(name = "DelayedCharges")
    protected Boolean delayedCharges;
    @XmlElement(name = "SalesEmailCc")
    protected EmailAddress salesEmailCc;
    @XmlElement(name = "SalesEmailBcc")
    protected EmailAddress salesEmailBcc;
    @XmlElement(name = "EmailCopyToCompany")
    protected Boolean emailCopyToCompany;
    @XmlElement(name = "AllowDeposit")
    protected Boolean allowDeposit;
    @XmlElement(name = "AllowDiscount")
    protected Boolean allowDiscount;
    @XmlElement(name = "DefaultDiscountAccount")
    protected String defaultDiscountAccount;
    @XmlElement(name = "AllowEstimates")
    protected Boolean allowEstimates;
    @XmlElement(name = "EstimateMessage")
    protected String estimateMessage;
    @XmlElement(name = "ETransactionEnabledStatus")
    protected ETransactionEnabledStatusEnum eTransactionEnabledStatus;
    @XmlElement(name = "ETransactionAttachPDF")
    protected Boolean eTransactionAttachPDF;
    @XmlElement(name = "ETransactionPaymentEnabled")
    protected Boolean eTransactionPaymentEnabled;
    @XmlElement(name = "IPNSupportEnabled")
    protected Boolean ipnSupportEnabled;
    @XmlElement(name = "InvoiceMessage")
    protected String invoiceMessage;
    @XmlElement(name = "AllowServiceDate")
    protected Boolean allowServiceDate;
    @XmlElement(name = "AllowShipping")
    protected Boolean allowShipping;
    @XmlElement(name = "DefaultShippingAccount")
    protected String defaultShippingAccount;
    @XmlElement(name = "DefaultItem")
    protected ReferenceType defaultItem;
    @XmlElement(name = "DefaultTerms")
    protected ReferenceType defaultTerms;
    @XmlElement(name = "DefaultDeliveryMethod")
    protected String defaultDeliveryMethod;
    @XmlElement(name = "AutoApplyCredit")
    protected Boolean autoApplyCredit;
    @XmlElement(name = "AutoApplyPayments")
    protected Boolean autoApplyPayments;
    @XmlElement(name = "PrintItemWithZeroAmount")
    protected Boolean printItemWithZeroAmount;
    @XmlElement(name = "DefaultShipMethodRef")
    protected ReferenceType defaultShipMethodRef;
    @XmlElement(name = "DefaultMarkup")
    protected BigDecimal defaultMarkup;
    @XmlElement(name = "TrackReimbursableExpensesAsIncome")
    protected Boolean trackReimbursableExpensesAsIncome;
    @XmlElement(name = "UsingSalesOrders")
    protected Boolean usingSalesOrders;
    @XmlElement(name = "UsingPriceLevels")
    protected Boolean usingPriceLevels;
    @XmlElement(name = "DefaultFOB")
    protected String defaultFOB;
    @XmlElement(name = "DefaultCustomerMessage")
    protected String defaultCustomerMessage;

    /**
     * Gets the value of the usingProgressInvoicing property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUsingProgressInvoicing() {
        return usingProgressInvoicing;
    }

    /**
     * Sets the value of the usingProgressInvoicing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUsingProgressInvoicing(Boolean value) {
        this.usingProgressInvoicing = value;
    }

    /**
     * Gets the value of the customField property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customField property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustomFieldDefinition }
     * 
     * 
     */
    public List<CustomFieldDefinition> getCustomField() {
        if (customField == null) {
            customField = new ArrayList<CustomFieldDefinition>();
        }
        return this.customField;
    }

    /**
     * Gets the value of the customTxnNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCustomTxnNumbers() {
        return customTxnNumbers;
    }

    /**
     * Sets the value of the customTxnNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCustomTxnNumbers(Boolean value) {
        this.customTxnNumbers = value;
    }

    /**
     * Gets the value of the delayedCharges property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDelayedCharges() {
        return delayedCharges;
    }

    /**
     * Sets the value of the delayedCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDelayedCharges(Boolean value) {
        this.delayedCharges = value;
    }

    /**
     * Gets the value of the salesEmailCc property.
     * 
     * @return
     *     possible object is
     *     {@link EmailAddress }
     *     
     */
    public EmailAddress getSalesEmailCc() {
        return salesEmailCc;
    }

    /**
     * Sets the value of the salesEmailCc property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmailAddress }
     *     
     */
    public void setSalesEmailCc(EmailAddress value) {
        this.salesEmailCc = value;
    }

    /**
     * Gets the value of the salesEmailBcc property.
     * 
     * @return
     *     possible object is
     *     {@link EmailAddress }
     *     
     */
    public EmailAddress getSalesEmailBcc() {
        return salesEmailBcc;
    }

    /**
     * Sets the value of the salesEmailBcc property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmailAddress }
     *     
     */
    public void setSalesEmailBcc(EmailAddress value) {
        this.salesEmailBcc = value;
    }

    /**
     * Gets the value of the emailCopyToCompany property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEmailCopyToCompany() {
        return emailCopyToCompany;
    }

    /**
     * Sets the value of the emailCopyToCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEmailCopyToCompany(Boolean value) {
        this.emailCopyToCompany = value;
    }

    /**
     * Gets the value of the allowDeposit property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowDeposit() {
        return allowDeposit;
    }

    /**
     * Sets the value of the allowDeposit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowDeposit(Boolean value) {
        this.allowDeposit = value;
    }

    /**
     * Gets the value of the allowDiscount property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowDiscount() {
        return allowDiscount;
    }

    /**
     * Sets the value of the allowDiscount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowDiscount(Boolean value) {
        this.allowDiscount = value;
    }

    /**
     * Gets the value of the defaultDiscountAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultDiscountAccount() {
        return defaultDiscountAccount;
    }

    /**
     * Sets the value of the defaultDiscountAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultDiscountAccount(String value) {
        this.defaultDiscountAccount = value;
    }

    /**
     * Gets the value of the allowEstimates property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowEstimates() {
        return allowEstimates;
    }

    /**
     * Sets the value of the allowEstimates property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowEstimates(Boolean value) {
        this.allowEstimates = value;
    }

    /**
     * Gets the value of the estimateMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstimateMessage() {
        return estimateMessage;
    }

    /**
     * Sets the value of the estimateMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstimateMessage(String value) {
        this.estimateMessage = value;
    }

    /**
     * Gets the value of the eTransactionEnabledStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ETransactionEnabledStatusEnum }
     *     
     */
    public ETransactionEnabledStatusEnum getETransactionEnabledStatus() {
        return eTransactionEnabledStatus;
    }

    /**
     * Sets the value of the eTransactionEnabledStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ETransactionEnabledStatusEnum }
     *     
     */
    public void setETransactionEnabledStatus(ETransactionEnabledStatusEnum value) {
        this.eTransactionEnabledStatus = value;
    }

    /**
     * Gets the value of the eTransactionAttachPDF property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isETransactionAttachPDF() {
        return eTransactionAttachPDF;
    }

    /**
     * Sets the value of the eTransactionAttachPDF property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setETransactionAttachPDF(Boolean value) {
        this.eTransactionAttachPDF = value;
    }

    /**
     * Gets the value of the eTransactionPaymentEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isETransactionPaymentEnabled() {
        return eTransactionPaymentEnabled;
    }

    /**
     * Sets the value of the eTransactionPaymentEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setETransactionPaymentEnabled(Boolean value) {
        this.eTransactionPaymentEnabled = value;
    }

    /**
     * Gets the value of the ipnSupportEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIPNSupportEnabled() {
        return ipnSupportEnabled;
    }

    /**
     * Sets the value of the ipnSupportEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIPNSupportEnabled(Boolean value) {
        this.ipnSupportEnabled = value;
    }

    /**
     * Gets the value of the invoiceMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceMessage() {
        return invoiceMessage;
    }

    /**
     * Sets the value of the invoiceMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceMessage(String value) {
        this.invoiceMessage = value;
    }

    /**
     * Gets the value of the allowServiceDate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowServiceDate() {
        return allowServiceDate;
    }

    /**
     * Sets the value of the allowServiceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowServiceDate(Boolean value) {
        this.allowServiceDate = value;
    }

    /**
     * Gets the value of the allowShipping property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowShipping() {
        return allowShipping;
    }

    /**
     * Sets the value of the allowShipping property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowShipping(Boolean value) {
        this.allowShipping = value;
    }

    /**
     * Gets the value of the defaultShippingAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultShippingAccount() {
        return defaultShippingAccount;
    }

    /**
     * Sets the value of the defaultShippingAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultShippingAccount(String value) {
        this.defaultShippingAccount = value;
    }

    /**
     * Gets the value of the defaultItem property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceType }
     *     
     */
    public ReferenceType getDefaultItem() {
        return defaultItem;
    }

    /**
     * Sets the value of the defaultItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceType }
     *     
     */
    public void setDefaultItem(ReferenceType value) {
        this.defaultItem = value;
    }

    /**
     * Gets the value of the defaultTerms property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceType }
     *     
     */
    public ReferenceType getDefaultTerms() {
        return defaultTerms;
    }

    /**
     * Sets the value of the defaultTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceType }
     *     
     */
    public void setDefaultTerms(ReferenceType value) {
        this.defaultTerms = value;
    }

    /**
     * Gets the value of the defaultDeliveryMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultDeliveryMethod() {
        return defaultDeliveryMethod;
    }

    /**
     * Sets the value of the defaultDeliveryMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultDeliveryMethod(String value) {
        this.defaultDeliveryMethod = value;
    }

    /**
     * Gets the value of the autoApplyCredit property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoApplyCredit() {
        return autoApplyCredit;
    }

    /**
     * Sets the value of the autoApplyCredit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoApplyCredit(Boolean value) {
        this.autoApplyCredit = value;
    }

    /**
     * Gets the value of the autoApplyPayments property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoApplyPayments() {
        return autoApplyPayments;
    }

    /**
     * Sets the value of the autoApplyPayments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoApplyPayments(Boolean value) {
        this.autoApplyPayments = value;
    }

    /**
     * Gets the value of the printItemWithZeroAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPrintItemWithZeroAmount() {
        return printItemWithZeroAmount;
    }

    /**
     * Sets the value of the printItemWithZeroAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPrintItemWithZeroAmount(Boolean value) {
        this.printItemWithZeroAmount = value;
    }

    /**
     * Gets the value of the defaultShipMethodRef property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceType }
     *     
     */
    public ReferenceType getDefaultShipMethodRef() {
        return defaultShipMethodRef;
    }

    /**
     * Sets the value of the defaultShipMethodRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceType }
     *     
     */
    public void setDefaultShipMethodRef(ReferenceType value) {
        this.defaultShipMethodRef = value;
    }

    /**
     * Gets the value of the defaultMarkup property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDefaultMarkup() {
        return defaultMarkup;
    }

    /**
     * Sets the value of the defaultMarkup property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDefaultMarkup(BigDecimal value) {
        this.defaultMarkup = value;
    }

    /**
     * Gets the value of the trackReimbursableExpensesAsIncome property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTrackReimbursableExpensesAsIncome() {
        return trackReimbursableExpensesAsIncome;
    }

    /**
     * Sets the value of the trackReimbursableExpensesAsIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTrackReimbursableExpensesAsIncome(Boolean value) {
        this.trackReimbursableExpensesAsIncome = value;
    }

    /**
     * Gets the value of the usingSalesOrders property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUsingSalesOrders() {
        return usingSalesOrders;
    }

    /**
     * Sets the value of the usingSalesOrders property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUsingSalesOrders(Boolean value) {
        this.usingSalesOrders = value;
    }

    /**
     * Gets the value of the usingPriceLevels property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUsingPriceLevels() {
        return usingPriceLevels;
    }

    /**
     * Sets the value of the usingPriceLevels property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUsingPriceLevels(Boolean value) {
        this.usingPriceLevels = value;
    }

    /**
     * Gets the value of the defaultFOB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultFOB() {
        return defaultFOB;
    }

    /**
     * Sets the value of the defaultFOB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultFOB(String value) {
        this.defaultFOB = value;
    }

    /**
     * Gets the value of the defaultCustomerMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultCustomerMessage() {
        return defaultCustomerMessage;
    }

    /**
     * Sets the value of the defaultCustomerMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultCustomerMessage(String value) {
        this.defaultCustomerMessage = value;
    }

    /**
     * Sets the value of the customField property.
     * 
     * @param customField
     *     allowed object is
     *     {@link CustomFieldDefinition }
     *     
     */
    public void setCustomField(List<CustomFieldDefinition> customField) {
        this.customField = customField;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final SalesFormsPrefs that = ((SalesFormsPrefs) object);
        {
            Boolean lhsUsingProgressInvoicing;
            lhsUsingProgressInvoicing = this.isUsingProgressInvoicing();
            Boolean rhsUsingProgressInvoicing;
            rhsUsingProgressInvoicing = that.isUsingProgressInvoicing();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "usingProgressInvoicing", lhsUsingProgressInvoicing), LocatorUtils.property(thatLocator, "usingProgressInvoicing", rhsUsingProgressInvoicing), lhsUsingProgressInvoicing, rhsUsingProgressInvoicing, (this.usingProgressInvoicing!= null), (that.usingProgressInvoicing!= null))) {
                return false;
            }
        }
        {
            List<CustomFieldDefinition> lhsCustomField;
            lhsCustomField = (((this.customField!= null)&&(!this.customField.isEmpty()))?this.getCustomField():null);
            List<CustomFieldDefinition> rhsCustomField;
            rhsCustomField = (((that.customField!= null)&&(!that.customField.isEmpty()))?that.getCustomField():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "customField", lhsCustomField), LocatorUtils.property(thatLocator, "customField", rhsCustomField), lhsCustomField, rhsCustomField, ((this.customField!= null)&&(!this.customField.isEmpty())), ((that.customField!= null)&&(!that.customField.isEmpty())))) {
                return false;
            }
        }
        {
            Boolean lhsCustomTxnNumbers;
            lhsCustomTxnNumbers = this.isCustomTxnNumbers();
            Boolean rhsCustomTxnNumbers;
            rhsCustomTxnNumbers = that.isCustomTxnNumbers();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "customTxnNumbers", lhsCustomTxnNumbers), LocatorUtils.property(thatLocator, "customTxnNumbers", rhsCustomTxnNumbers), lhsCustomTxnNumbers, rhsCustomTxnNumbers, (this.customTxnNumbers!= null), (that.customTxnNumbers!= null))) {
                return false;
            }
        }
        {
            Boolean lhsDelayedCharges;
            lhsDelayedCharges = this.isDelayedCharges();
            Boolean rhsDelayedCharges;
            rhsDelayedCharges = that.isDelayedCharges();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "delayedCharges", lhsDelayedCharges), LocatorUtils.property(thatLocator, "delayedCharges", rhsDelayedCharges), lhsDelayedCharges, rhsDelayedCharges, (this.delayedCharges!= null), (that.delayedCharges!= null))) {
                return false;
            }
        }
        {
            EmailAddress lhsSalesEmailCc;
            lhsSalesEmailCc = this.getSalesEmailCc();
            EmailAddress rhsSalesEmailCc;
            rhsSalesEmailCc = that.getSalesEmailCc();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "salesEmailCc", lhsSalesEmailCc), LocatorUtils.property(thatLocator, "salesEmailCc", rhsSalesEmailCc), lhsSalesEmailCc, rhsSalesEmailCc, (this.salesEmailCc!= null), (that.salesEmailCc!= null))) {
                return false;
            }
        }
        {
            EmailAddress lhsSalesEmailBcc;
            lhsSalesEmailBcc = this.getSalesEmailBcc();
            EmailAddress rhsSalesEmailBcc;
            rhsSalesEmailBcc = that.getSalesEmailBcc();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "salesEmailBcc", lhsSalesEmailBcc), LocatorUtils.property(thatLocator, "salesEmailBcc", rhsSalesEmailBcc), lhsSalesEmailBcc, rhsSalesEmailBcc, (this.salesEmailBcc!= null), (that.salesEmailBcc!= null))) {
                return false;
            }
        }
        {
            Boolean lhsEmailCopyToCompany;
            lhsEmailCopyToCompany = this.isEmailCopyToCompany();
            Boolean rhsEmailCopyToCompany;
            rhsEmailCopyToCompany = that.isEmailCopyToCompany();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "emailCopyToCompany", lhsEmailCopyToCompany), LocatorUtils.property(thatLocator, "emailCopyToCompany", rhsEmailCopyToCompany), lhsEmailCopyToCompany, rhsEmailCopyToCompany, (this.emailCopyToCompany!= null), (that.emailCopyToCompany!= null))) {
                return false;
            }
        }
        {
            Boolean lhsAllowDeposit;
            lhsAllowDeposit = this.isAllowDeposit();
            Boolean rhsAllowDeposit;
            rhsAllowDeposit = that.isAllowDeposit();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "allowDeposit", lhsAllowDeposit), LocatorUtils.property(thatLocator, "allowDeposit", rhsAllowDeposit), lhsAllowDeposit, rhsAllowDeposit, (this.allowDeposit!= null), (that.allowDeposit!= null))) {
                return false;
            }
        }
        {
            Boolean lhsAllowDiscount;
            lhsAllowDiscount = this.isAllowDiscount();
            Boolean rhsAllowDiscount;
            rhsAllowDiscount = that.isAllowDiscount();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "allowDiscount", lhsAllowDiscount), LocatorUtils.property(thatLocator, "allowDiscount", rhsAllowDiscount), lhsAllowDiscount, rhsAllowDiscount, (this.allowDiscount!= null), (that.allowDiscount!= null))) {
                return false;
            }
        }
        {
            String lhsDefaultDiscountAccount;
            lhsDefaultDiscountAccount = this.getDefaultDiscountAccount();
            String rhsDefaultDiscountAccount;
            rhsDefaultDiscountAccount = that.getDefaultDiscountAccount();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "defaultDiscountAccount", lhsDefaultDiscountAccount), LocatorUtils.property(thatLocator, "defaultDiscountAccount", rhsDefaultDiscountAccount), lhsDefaultDiscountAccount, rhsDefaultDiscountAccount, (this.defaultDiscountAccount!= null), (that.defaultDiscountAccount!= null))) {
                return false;
            }
        }
        {
            Boolean lhsAllowEstimates;
            lhsAllowEstimates = this.isAllowEstimates();
            Boolean rhsAllowEstimates;
            rhsAllowEstimates = that.isAllowEstimates();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "allowEstimates", lhsAllowEstimates), LocatorUtils.property(thatLocator, "allowEstimates", rhsAllowEstimates), lhsAllowEstimates, rhsAllowEstimates, (this.allowEstimates!= null), (that.allowEstimates!= null))) {
                return false;
            }
        }
        {
            String lhsEstimateMessage;
            lhsEstimateMessage = this.getEstimateMessage();
            String rhsEstimateMessage;
            rhsEstimateMessage = that.getEstimateMessage();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "estimateMessage", lhsEstimateMessage), LocatorUtils.property(thatLocator, "estimateMessage", rhsEstimateMessage), lhsEstimateMessage, rhsEstimateMessage, (this.estimateMessage!= null), (that.estimateMessage!= null))) {
                return false;
            }
        }
        {
            ETransactionEnabledStatusEnum lhsETransactionEnabledStatus;
            lhsETransactionEnabledStatus = this.getETransactionEnabledStatus();
            ETransactionEnabledStatusEnum rhsETransactionEnabledStatus;
            rhsETransactionEnabledStatus = that.getETransactionEnabledStatus();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "eTransactionEnabledStatus", lhsETransactionEnabledStatus), LocatorUtils.property(thatLocator, "eTransactionEnabledStatus", rhsETransactionEnabledStatus), lhsETransactionEnabledStatus, rhsETransactionEnabledStatus, (this.eTransactionEnabledStatus!= null), (that.eTransactionEnabledStatus!= null))) {
                return false;
            }
        }
        {
            Boolean lhsETransactionAttachPDF;
            lhsETransactionAttachPDF = this.isETransactionAttachPDF();
            Boolean rhsETransactionAttachPDF;
            rhsETransactionAttachPDF = that.isETransactionAttachPDF();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "eTransactionAttachPDF", lhsETransactionAttachPDF), LocatorUtils.property(thatLocator, "eTransactionAttachPDF", rhsETransactionAttachPDF), lhsETransactionAttachPDF, rhsETransactionAttachPDF, (this.eTransactionAttachPDF!= null), (that.eTransactionAttachPDF!= null))) {
                return false;
            }
        }
        {
            Boolean lhsETransactionPaymentEnabled;
            lhsETransactionPaymentEnabled = this.isETransactionPaymentEnabled();
            Boolean rhsETransactionPaymentEnabled;
            rhsETransactionPaymentEnabled = that.isETransactionPaymentEnabled();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "eTransactionPaymentEnabled", lhsETransactionPaymentEnabled), LocatorUtils.property(thatLocator, "eTransactionPaymentEnabled", rhsETransactionPaymentEnabled), lhsETransactionPaymentEnabled, rhsETransactionPaymentEnabled, (this.eTransactionPaymentEnabled!= null), (that.eTransactionPaymentEnabled!= null))) {
                return false;
            }
        }
        {
            Boolean lhsIPNSupportEnabled;
            lhsIPNSupportEnabled = this.isIPNSupportEnabled();
            Boolean rhsIPNSupportEnabled;
            rhsIPNSupportEnabled = that.isIPNSupportEnabled();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "ipnSupportEnabled", lhsIPNSupportEnabled), LocatorUtils.property(thatLocator, "ipnSupportEnabled", rhsIPNSupportEnabled), lhsIPNSupportEnabled, rhsIPNSupportEnabled, (this.ipnSupportEnabled!= null), (that.ipnSupportEnabled!= null))) {
                return false;
            }
        }
        {
            String lhsInvoiceMessage;
            lhsInvoiceMessage = this.getInvoiceMessage();
            String rhsInvoiceMessage;
            rhsInvoiceMessage = that.getInvoiceMessage();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "invoiceMessage", lhsInvoiceMessage), LocatorUtils.property(thatLocator, "invoiceMessage", rhsInvoiceMessage), lhsInvoiceMessage, rhsInvoiceMessage, (this.invoiceMessage!= null), (that.invoiceMessage!= null))) {
                return false;
            }
        }
        {
            Boolean lhsAllowServiceDate;
            lhsAllowServiceDate = this.isAllowServiceDate();
            Boolean rhsAllowServiceDate;
            rhsAllowServiceDate = that.isAllowServiceDate();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "allowServiceDate", lhsAllowServiceDate), LocatorUtils.property(thatLocator, "allowServiceDate", rhsAllowServiceDate), lhsAllowServiceDate, rhsAllowServiceDate, (this.allowServiceDate!= null), (that.allowServiceDate!= null))) {
                return false;
            }
        }
        {
            Boolean lhsAllowShipping;
            lhsAllowShipping = this.isAllowShipping();
            Boolean rhsAllowShipping;
            rhsAllowShipping = that.isAllowShipping();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "allowShipping", lhsAllowShipping), LocatorUtils.property(thatLocator, "allowShipping", rhsAllowShipping), lhsAllowShipping, rhsAllowShipping, (this.allowShipping!= null), (that.allowShipping!= null))) {
                return false;
            }
        }
        {
            String lhsDefaultShippingAccount;
            lhsDefaultShippingAccount = this.getDefaultShippingAccount();
            String rhsDefaultShippingAccount;
            rhsDefaultShippingAccount = that.getDefaultShippingAccount();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "defaultShippingAccount", lhsDefaultShippingAccount), LocatorUtils.property(thatLocator, "defaultShippingAccount", rhsDefaultShippingAccount), lhsDefaultShippingAccount, rhsDefaultShippingAccount, (this.defaultShippingAccount!= null), (that.defaultShippingAccount!= null))) {
                return false;
            }
        }
        {
            ReferenceType lhsDefaultItem;
            lhsDefaultItem = this.getDefaultItem();
            ReferenceType rhsDefaultItem;
            rhsDefaultItem = that.getDefaultItem();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "defaultItem", lhsDefaultItem), LocatorUtils.property(thatLocator, "defaultItem", rhsDefaultItem), lhsDefaultItem, rhsDefaultItem, (this.defaultItem!= null), (that.defaultItem!= null))) {
                return false;
            }
        }
        {
            ReferenceType lhsDefaultTerms;
            lhsDefaultTerms = this.getDefaultTerms();
            ReferenceType rhsDefaultTerms;
            rhsDefaultTerms = that.getDefaultTerms();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "defaultTerms", lhsDefaultTerms), LocatorUtils.property(thatLocator, "defaultTerms", rhsDefaultTerms), lhsDefaultTerms, rhsDefaultTerms, (this.defaultTerms!= null), (that.defaultTerms!= null))) {
                return false;
            }
        }
        {
            String lhsDefaultDeliveryMethod;
            lhsDefaultDeliveryMethod = this.getDefaultDeliveryMethod();
            String rhsDefaultDeliveryMethod;
            rhsDefaultDeliveryMethod = that.getDefaultDeliveryMethod();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "defaultDeliveryMethod", lhsDefaultDeliveryMethod), LocatorUtils.property(thatLocator, "defaultDeliveryMethod", rhsDefaultDeliveryMethod), lhsDefaultDeliveryMethod, rhsDefaultDeliveryMethod, (this.defaultDeliveryMethod!= null), (that.defaultDeliveryMethod!= null))) {
                return false;
            }
        }
        {
            Boolean lhsAutoApplyCredit;
            lhsAutoApplyCredit = this.isAutoApplyCredit();
            Boolean rhsAutoApplyCredit;
            rhsAutoApplyCredit = that.isAutoApplyCredit();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "autoApplyCredit", lhsAutoApplyCredit), LocatorUtils.property(thatLocator, "autoApplyCredit", rhsAutoApplyCredit), lhsAutoApplyCredit, rhsAutoApplyCredit, (this.autoApplyCredit!= null), (that.autoApplyCredit!= null))) {
                return false;
            }
        }
        {
            Boolean lhsAutoApplyPayments;
            lhsAutoApplyPayments = this.isAutoApplyPayments();
            Boolean rhsAutoApplyPayments;
            rhsAutoApplyPayments = that.isAutoApplyPayments();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "autoApplyPayments", lhsAutoApplyPayments), LocatorUtils.property(thatLocator, "autoApplyPayments", rhsAutoApplyPayments), lhsAutoApplyPayments, rhsAutoApplyPayments, (this.autoApplyPayments!= null), (that.autoApplyPayments!= null))) {
                return false;
            }
        }
        {
            Boolean lhsPrintItemWithZeroAmount;
            lhsPrintItemWithZeroAmount = this.isPrintItemWithZeroAmount();
            Boolean rhsPrintItemWithZeroAmount;
            rhsPrintItemWithZeroAmount = that.isPrintItemWithZeroAmount();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "printItemWithZeroAmount", lhsPrintItemWithZeroAmount), LocatorUtils.property(thatLocator, "printItemWithZeroAmount", rhsPrintItemWithZeroAmount), lhsPrintItemWithZeroAmount, rhsPrintItemWithZeroAmount, (this.printItemWithZeroAmount!= null), (that.printItemWithZeroAmount!= null))) {
                return false;
            }
        }
        {
            ReferenceType lhsDefaultShipMethodRef;
            lhsDefaultShipMethodRef = this.getDefaultShipMethodRef();
            ReferenceType rhsDefaultShipMethodRef;
            rhsDefaultShipMethodRef = that.getDefaultShipMethodRef();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "defaultShipMethodRef", lhsDefaultShipMethodRef), LocatorUtils.property(thatLocator, "defaultShipMethodRef", rhsDefaultShipMethodRef), lhsDefaultShipMethodRef, rhsDefaultShipMethodRef, (this.defaultShipMethodRef!= null), (that.defaultShipMethodRef!= null))) {
                return false;
            }
        }
        {
            BigDecimal lhsDefaultMarkup;
            lhsDefaultMarkup = this.getDefaultMarkup();
            BigDecimal rhsDefaultMarkup;
            rhsDefaultMarkup = that.getDefaultMarkup();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "defaultMarkup", lhsDefaultMarkup), LocatorUtils.property(thatLocator, "defaultMarkup", rhsDefaultMarkup), lhsDefaultMarkup, rhsDefaultMarkup, (this.defaultMarkup!= null), (that.defaultMarkup!= null))) {
                return false;
            }
        }
        {
            Boolean lhsTrackReimbursableExpensesAsIncome;
            lhsTrackReimbursableExpensesAsIncome = this.isTrackReimbursableExpensesAsIncome();
            Boolean rhsTrackReimbursableExpensesAsIncome;
            rhsTrackReimbursableExpensesAsIncome = that.isTrackReimbursableExpensesAsIncome();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "trackReimbursableExpensesAsIncome", lhsTrackReimbursableExpensesAsIncome), LocatorUtils.property(thatLocator, "trackReimbursableExpensesAsIncome", rhsTrackReimbursableExpensesAsIncome), lhsTrackReimbursableExpensesAsIncome, rhsTrackReimbursableExpensesAsIncome, (this.trackReimbursableExpensesAsIncome!= null), (that.trackReimbursableExpensesAsIncome!= null))) {
                return false;
            }
        }
        {
            Boolean lhsUsingSalesOrders;
            lhsUsingSalesOrders = this.isUsingSalesOrders();
            Boolean rhsUsingSalesOrders;
            rhsUsingSalesOrders = that.isUsingSalesOrders();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "usingSalesOrders", lhsUsingSalesOrders), LocatorUtils.property(thatLocator, "usingSalesOrders", rhsUsingSalesOrders), lhsUsingSalesOrders, rhsUsingSalesOrders, (this.usingSalesOrders!= null), (that.usingSalesOrders!= null))) {
                return false;
            }
        }
        {
            Boolean lhsUsingPriceLevels;
            lhsUsingPriceLevels = this.isUsingPriceLevels();
            Boolean rhsUsingPriceLevels;
            rhsUsingPriceLevels = that.isUsingPriceLevels();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "usingPriceLevels", lhsUsingPriceLevels), LocatorUtils.property(thatLocator, "usingPriceLevels", rhsUsingPriceLevels), lhsUsingPriceLevels, rhsUsingPriceLevels, (this.usingPriceLevels!= null), (that.usingPriceLevels!= null))) {
                return false;
            }
        }
        {
            String lhsDefaultFOB;
            lhsDefaultFOB = this.getDefaultFOB();
            String rhsDefaultFOB;
            rhsDefaultFOB = that.getDefaultFOB();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "defaultFOB", lhsDefaultFOB), LocatorUtils.property(thatLocator, "defaultFOB", rhsDefaultFOB), lhsDefaultFOB, rhsDefaultFOB, (this.defaultFOB!= null), (that.defaultFOB!= null))) {
                return false;
            }
        }
        {
            String lhsDefaultCustomerMessage;
            lhsDefaultCustomerMessage = this.getDefaultCustomerMessage();
            String rhsDefaultCustomerMessage;
            rhsDefaultCustomerMessage = that.getDefaultCustomerMessage();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "defaultCustomerMessage", lhsDefaultCustomerMessage), LocatorUtils.property(thatLocator, "defaultCustomerMessage", rhsDefaultCustomerMessage), lhsDefaultCustomerMessage, rhsDefaultCustomerMessage, (this.defaultCustomerMessage!= null), (that.defaultCustomerMessage!= null))) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
        int currentHashCode = 1;
        {
            Boolean theUsingProgressInvoicing;
            theUsingProgressInvoicing = this.isUsingProgressInvoicing();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "usingProgressInvoicing", theUsingProgressInvoicing), currentHashCode, theUsingProgressInvoicing, (this.usingProgressInvoicing!= null));
        }
        {
            List<CustomFieldDefinition> theCustomField;
            theCustomField = (((this.customField!= null)&&(!this.customField.isEmpty()))?this.getCustomField():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "customField", theCustomField), currentHashCode, theCustomField, ((this.customField!= null)&&(!this.customField.isEmpty())));
        }
        {
            Boolean theCustomTxnNumbers;
            theCustomTxnNumbers = this.isCustomTxnNumbers();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "customTxnNumbers", theCustomTxnNumbers), currentHashCode, theCustomTxnNumbers, (this.customTxnNumbers!= null));
        }
        {
            Boolean theDelayedCharges;
            theDelayedCharges = this.isDelayedCharges();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "delayedCharges", theDelayedCharges), currentHashCode, theDelayedCharges, (this.delayedCharges!= null));
        }
        {
            EmailAddress theSalesEmailCc;
            theSalesEmailCc = this.getSalesEmailCc();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "salesEmailCc", theSalesEmailCc), currentHashCode, theSalesEmailCc, (this.salesEmailCc!= null));
        }
        {
            EmailAddress theSalesEmailBcc;
            theSalesEmailBcc = this.getSalesEmailBcc();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "salesEmailBcc", theSalesEmailBcc), currentHashCode, theSalesEmailBcc, (this.salesEmailBcc!= null));
        }
        {
            Boolean theEmailCopyToCompany;
            theEmailCopyToCompany = this.isEmailCopyToCompany();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "emailCopyToCompany", theEmailCopyToCompany), currentHashCode, theEmailCopyToCompany, (this.emailCopyToCompany!= null));
        }
        {
            Boolean theAllowDeposit;
            theAllowDeposit = this.isAllowDeposit();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "allowDeposit", theAllowDeposit), currentHashCode, theAllowDeposit, (this.allowDeposit!= null));
        }
        {
            Boolean theAllowDiscount;
            theAllowDiscount = this.isAllowDiscount();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "allowDiscount", theAllowDiscount), currentHashCode, theAllowDiscount, (this.allowDiscount!= null));
        }
        {
            String theDefaultDiscountAccount;
            theDefaultDiscountAccount = this.getDefaultDiscountAccount();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "defaultDiscountAccount", theDefaultDiscountAccount), currentHashCode, theDefaultDiscountAccount, (this.defaultDiscountAccount!= null));
        }
        {
            Boolean theAllowEstimates;
            theAllowEstimates = this.isAllowEstimates();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "allowEstimates", theAllowEstimates), currentHashCode, theAllowEstimates, (this.allowEstimates!= null));
        }
        {
            String theEstimateMessage;
            theEstimateMessage = this.getEstimateMessage();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "estimateMessage", theEstimateMessage), currentHashCode, theEstimateMessage, (this.estimateMessage!= null));
        }
        {
            ETransactionEnabledStatusEnum theETransactionEnabledStatus;
            theETransactionEnabledStatus = this.getETransactionEnabledStatus();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "eTransactionEnabledStatus", theETransactionEnabledStatus), currentHashCode, theETransactionEnabledStatus, (this.eTransactionEnabledStatus!= null));
        }
        {
            Boolean theETransactionAttachPDF;
            theETransactionAttachPDF = this.isETransactionAttachPDF();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "eTransactionAttachPDF", theETransactionAttachPDF), currentHashCode, theETransactionAttachPDF, (this.eTransactionAttachPDF!= null));
        }
        {
            Boolean theETransactionPaymentEnabled;
            theETransactionPaymentEnabled = this.isETransactionPaymentEnabled();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "eTransactionPaymentEnabled", theETransactionPaymentEnabled), currentHashCode, theETransactionPaymentEnabled, (this.eTransactionPaymentEnabled!= null));
        }
        {
            Boolean theIPNSupportEnabled;
            theIPNSupportEnabled = this.isIPNSupportEnabled();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "ipnSupportEnabled", theIPNSupportEnabled), currentHashCode, theIPNSupportEnabled, (this.ipnSupportEnabled!= null));
        }
        {
            String theInvoiceMessage;
            theInvoiceMessage = this.getInvoiceMessage();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "invoiceMessage", theInvoiceMessage), currentHashCode, theInvoiceMessage, (this.invoiceMessage!= null));
        }
        {
            Boolean theAllowServiceDate;
            theAllowServiceDate = this.isAllowServiceDate();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "allowServiceDate", theAllowServiceDate), currentHashCode, theAllowServiceDate, (this.allowServiceDate!= null));
        }
        {
            Boolean theAllowShipping;
            theAllowShipping = this.isAllowShipping();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "allowShipping", theAllowShipping), currentHashCode, theAllowShipping, (this.allowShipping!= null));
        }
        {
            String theDefaultShippingAccount;
            theDefaultShippingAccount = this.getDefaultShippingAccount();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "defaultShippingAccount", theDefaultShippingAccount), currentHashCode, theDefaultShippingAccount, (this.defaultShippingAccount!= null));
        }
        {
            ReferenceType theDefaultItem;
            theDefaultItem = this.getDefaultItem();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "defaultItem", theDefaultItem), currentHashCode, theDefaultItem, (this.defaultItem!= null));
        }
        {
            ReferenceType theDefaultTerms;
            theDefaultTerms = this.getDefaultTerms();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "defaultTerms", theDefaultTerms), currentHashCode, theDefaultTerms, (this.defaultTerms!= null));
        }
        {
            String theDefaultDeliveryMethod;
            theDefaultDeliveryMethod = this.getDefaultDeliveryMethod();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "defaultDeliveryMethod", theDefaultDeliveryMethod), currentHashCode, theDefaultDeliveryMethod, (this.defaultDeliveryMethod!= null));
        }
        {
            Boolean theAutoApplyCredit;
            theAutoApplyCredit = this.isAutoApplyCredit();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "autoApplyCredit", theAutoApplyCredit), currentHashCode, theAutoApplyCredit, (this.autoApplyCredit!= null));
        }
        {
            Boolean theAutoApplyPayments;
            theAutoApplyPayments = this.isAutoApplyPayments();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "autoApplyPayments", theAutoApplyPayments), currentHashCode, theAutoApplyPayments, (this.autoApplyPayments!= null));
        }
        {
            Boolean thePrintItemWithZeroAmount;
            thePrintItemWithZeroAmount = this.isPrintItemWithZeroAmount();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "printItemWithZeroAmount", thePrintItemWithZeroAmount), currentHashCode, thePrintItemWithZeroAmount, (this.printItemWithZeroAmount!= null));
        }
        {
            ReferenceType theDefaultShipMethodRef;
            theDefaultShipMethodRef = this.getDefaultShipMethodRef();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "defaultShipMethodRef", theDefaultShipMethodRef), currentHashCode, theDefaultShipMethodRef, (this.defaultShipMethodRef!= null));
        }
        {
            BigDecimal theDefaultMarkup;
            theDefaultMarkup = this.getDefaultMarkup();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "defaultMarkup", theDefaultMarkup), currentHashCode, theDefaultMarkup, (this.defaultMarkup!= null));
        }
        {
            Boolean theTrackReimbursableExpensesAsIncome;
            theTrackReimbursableExpensesAsIncome = this.isTrackReimbursableExpensesAsIncome();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "trackReimbursableExpensesAsIncome", theTrackReimbursableExpensesAsIncome), currentHashCode, theTrackReimbursableExpensesAsIncome, (this.trackReimbursableExpensesAsIncome!= null));
        }
        {
            Boolean theUsingSalesOrders;
            theUsingSalesOrders = this.isUsingSalesOrders();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "usingSalesOrders", theUsingSalesOrders), currentHashCode, theUsingSalesOrders, (this.usingSalesOrders!= null));
        }
        {
            Boolean theUsingPriceLevels;
            theUsingPriceLevels = this.isUsingPriceLevels();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "usingPriceLevels", theUsingPriceLevels), currentHashCode, theUsingPriceLevels, (this.usingPriceLevels!= null));
        }
        {
            String theDefaultFOB;
            theDefaultFOB = this.getDefaultFOB();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "defaultFOB", theDefaultFOB), currentHashCode, theDefaultFOB, (this.defaultFOB!= null));
        }
        {
            String theDefaultCustomerMessage;
            theDefaultCustomerMessage = this.getDefaultCustomerMessage();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "defaultCustomerMessage", theDefaultCustomerMessage), currentHashCode, theDefaultCustomerMessage, (this.defaultCustomerMessage!= null));
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
