//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.18 at 04:20:25 PM IST 
//


package com.intuit.ipp.data;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 *                 Product: QBW
 *                 Description: Wrapper object for specifying both version of the objects
 *                 If there is any warnings on a object basis that is also send back
 *                 This object is output object only
 *             
 * 
 * <p>Java class for SyncError complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SyncError"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Error" type="{http://schema.intuit.com/finance/v3}Error" minOccurs="0"/&gt;
 *         &lt;element name="CloudVersion" type="{http://schema.intuit.com/finance/v3}SyncObject" minOccurs="0"/&gt;
 *         &lt;element name="QBVersion" type="{http://schema.intuit.com/finance/v3}SyncObject" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="AppToken" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SyncError", propOrder = {
    "error",
    "cloudVersion",
    "qbVersion"
})
public class SyncError
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Error")
    protected Error error;
    @XmlElement(name = "CloudVersion")
    protected SyncObject cloudVersion;
    @XmlElement(name = "QBVersion")
    protected SyncObject qbVersion;
    @XmlAttribute(name = "Type")
    protected String type;
    @XmlAttribute(name = "AppToken")
    protected String appToken;

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link Error }
     *     
     */
    public Error getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link Error }
     *     
     */
    public void setError(Error value) {
        this.error = value;
    }

    /**
     * Gets the value of the cloudVersion property.
     * 
     * @return
     *     possible object is
     *     {@link SyncObject }
     *     
     */
    public SyncObject getCloudVersion() {
        return cloudVersion;
    }

    /**
     * Sets the value of the cloudVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link SyncObject }
     *     
     */
    public void setCloudVersion(SyncObject value) {
        this.cloudVersion = value;
    }

    /**
     * Gets the value of the qbVersion property.
     * 
     * @return
     *     possible object is
     *     {@link SyncObject }
     *     
     */
    public SyncObject getQBVersion() {
        return qbVersion;
    }

    /**
     * Sets the value of the qbVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link SyncObject }
     *     
     */
    public void setQBVersion(SyncObject value) {
        this.qbVersion = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the appToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppToken() {
        return appToken;
    }

    /**
     * Sets the value of the appToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppToken(String value) {
        this.appToken = value;
    }

}
