//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.18 at 04:20:25 PM IST 
//


package com.intuit.ipp.data;

import java.io.Serializable;
import java.util.Date;
import com.intuit.sb.cdm.util.v3.DateTimeAdapter;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 *        			 Product: QBW
 *         		 Description: Provides upload/writeback activity for a given period of time. Query activity using 
 *         		 			  StartSyncTMS OR EndSyncTMS
 *       		
 * 
 * <p>Java class for SyncActivity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SyncActivity"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://schema.intuit.com/finance/v3}IntuitEntity"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="LatestUploadDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="LatestWriteBackDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="SyncType" type="{http://schema.intuit.com/finance/v3}SyncType" minOccurs="0"/&gt;
 *         &lt;element name="StartSyncTMS" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="EndSyncTMS" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="EntityName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EntityRowCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SyncActivity", propOrder = {
    "latestUploadDateTime",
    "latestWriteBackDateTime",
    "syncType",
    "startSyncTMS",
    "endSyncTMS",
    "entityName",
    "entityRowCount"
})
public class SyncActivity
    extends IntuitEntity
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "LatestUploadDateTime", type = String.class)
    @XmlJavaTypeAdapter(DateTimeAdapter.class)
    @XmlSchemaType(name = "dateTime")
    protected Date latestUploadDateTime;
    @XmlElement(name = "LatestWriteBackDateTime", type = String.class)
    @XmlJavaTypeAdapter(DateTimeAdapter.class)
    @XmlSchemaType(name = "dateTime")
    protected Date latestWriteBackDateTime;
    @XmlElement(name = "SyncType")
    @XmlSchemaType(name = "string")
    protected SyncType syncType;
    @XmlElement(name = "StartSyncTMS", type = String.class)
    @XmlJavaTypeAdapter(DateTimeAdapter.class)
    @XmlSchemaType(name = "dateTime")
    protected Date startSyncTMS;
    @XmlElement(name = "EndSyncTMS", type = String.class)
    @XmlJavaTypeAdapter(DateTimeAdapter.class)
    @XmlSchemaType(name = "dateTime")
    protected Date endSyncTMS;
    @XmlElement(name = "EntityName")
    protected String entityName;
    @XmlElement(name = "EntityRowCount")
    protected Integer entityRowCount;

    /**
     * Gets the value of the latestUploadDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getLatestUploadDateTime() {
        return latestUploadDateTime;
    }

    /**
     * Sets the value of the latestUploadDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLatestUploadDateTime(Date value) {
        this.latestUploadDateTime = value;
    }

    /**
     * Gets the value of the latestWriteBackDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getLatestWriteBackDateTime() {
        return latestWriteBackDateTime;
    }

    /**
     * Sets the value of the latestWriteBackDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLatestWriteBackDateTime(Date value) {
        this.latestWriteBackDateTime = value;
    }

    /**
     * Gets the value of the syncType property.
     * 
     * @return
     *     possible object is
     *     {@link SyncType }
     *     
     */
    public SyncType getSyncType() {
        return syncType;
    }

    /**
     * Sets the value of the syncType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SyncType }
     *     
     */
    public void setSyncType(SyncType value) {
        this.syncType = value;
    }

    /**
     * Gets the value of the startSyncTMS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getStartSyncTMS() {
        return startSyncTMS;
    }

    /**
     * Sets the value of the startSyncTMS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartSyncTMS(Date value) {
        this.startSyncTMS = value;
    }

    /**
     * Gets the value of the endSyncTMS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getEndSyncTMS() {
        return endSyncTMS;
    }

    /**
     * Sets the value of the endSyncTMS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndSyncTMS(Date value) {
        this.endSyncTMS = value;
    }

    /**
     * Gets the value of the entityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityName() {
        return entityName;
    }

    /**
     * Sets the value of the entityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityName(String value) {
        this.entityName = value;
    }

    /**
     * Gets the value of the entityRowCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEntityRowCount() {
        return entityRowCount;
    }

    /**
     * Sets the value of the entityRowCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEntityRowCount(Integer value) {
        this.entityRowCount = value;
    }

}
