/*******************************************************************************
 * Copyright (c) 2017 Intuit
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * 	http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.14 at 04:24:27 PM PST 
//


package com.intuit.ipp.data;

import java.io.Serializable;
import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.intuit.sb.cdm.util.v3.DateAdapter;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * 
 * 				Product: ALL
 * 				Description: Represents a tax agency to whom sales/purchase/VAT taxes collected are paid
 * 			
 * 
 * <p>Java class for TaxAgency complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaxAgency">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schema.intuit.com/finance/v3}Vendor">
 *       &lt;sequence>
 *         &lt;element name="SalesTaxCodeRef" type="{http://schema.intuit.com/finance/v3}ReferenceType" minOccurs="0"/>
 *         &lt;element name="SalesTaxCountry" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SalesTaxReturnRef" type="{http://schema.intuit.com/finance/v3}ReferenceType" minOccurs="0"/>
 *         &lt;element name="TaxRegistrationNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReportingPeriod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TaxTrackedOnPurchases" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="TaxOnPurchasesAccountRef" type="{http://schema.intuit.com/finance/v3}ReferenceType" minOccurs="0"/>
 *         &lt;element name="TaxTrackedOnSales" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="TaxTrackedOnSalesAccountRef" type="{http://schema.intuit.com/finance/v3}ReferenceType" minOccurs="0"/>
 *         &lt;element name="TaxOnTax" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="LastFileDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="TaxAgencyExt" type="{http://schema.intuit.com/finance/v3}IntuitAnyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaxAgency", propOrder = {
    "salesTaxCodeRef",
    "salesTaxCountry",
    "salesTaxReturnRef",
    "taxRegistrationNumber",
    "reportingPeriod",
    "taxTrackedOnPurchases",
    "taxOnPurchasesAccountRef",
    "taxTrackedOnSales",
    "taxTrackedOnSalesAccountRef",
    "taxOnTax",
    "lastFileDate",
    "taxAgencyExt"
})
public class TaxAgency
    extends Vendor
    implements Serializable, Equals, HashCode
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "SalesTaxCodeRef")
    protected ReferenceType salesTaxCodeRef;
    @XmlElement(name = "SalesTaxCountry")
    protected String salesTaxCountry;
    @XmlElement(name = "SalesTaxReturnRef")
    protected ReferenceType salesTaxReturnRef;
    @XmlElement(name = "TaxRegistrationNumber")
    protected String taxRegistrationNumber;
    @XmlElement(name = "ReportingPeriod")
    protected String reportingPeriod;
    @XmlElement(name = "TaxTrackedOnPurchases")
    protected Boolean taxTrackedOnPurchases;
    @XmlElement(name = "TaxOnPurchasesAccountRef")
    protected ReferenceType taxOnPurchasesAccountRef;
    @XmlElement(name = "TaxTrackedOnSales")
    protected Boolean taxTrackedOnSales;
    @XmlElement(name = "TaxTrackedOnSalesAccountRef")
    protected ReferenceType taxTrackedOnSalesAccountRef;
    @XmlElement(name = "TaxOnTax")
    protected Boolean taxOnTax;
    @XmlElement(name = "LastFileDate", type = String.class)
    @XmlJavaTypeAdapter(DateAdapter.class)
    @XmlSchemaType(name = "date")
    protected Date lastFileDate;
    @XmlElement(name = "TaxAgencyExt")
    protected IntuitAnyType taxAgencyExt;

    /**
     * Gets the value of the salesTaxCodeRef property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceType }
     *     
     */
    public ReferenceType getSalesTaxCodeRef() {
        return salesTaxCodeRef;
    }

    /**
     * Sets the value of the salesTaxCodeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceType }
     *     
     */
    public void setSalesTaxCodeRef(ReferenceType value) {
        this.salesTaxCodeRef = value;
    }

    /**
     * Gets the value of the salesTaxCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesTaxCountry() {
        return salesTaxCountry;
    }

    /**
     * Sets the value of the salesTaxCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesTaxCountry(String value) {
        this.salesTaxCountry = value;
    }

    /**
     * Gets the value of the salesTaxReturnRef property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceType }
     *     
     */
    public ReferenceType getSalesTaxReturnRef() {
        return salesTaxReturnRef;
    }

    /**
     * Sets the value of the salesTaxReturnRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceType }
     *     
     */
    public void setSalesTaxReturnRef(ReferenceType value) {
        this.salesTaxReturnRef = value;
    }

    /**
     * Gets the value of the taxRegistrationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxRegistrationNumber() {
        return taxRegistrationNumber;
    }

    /**
     * Sets the value of the taxRegistrationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxRegistrationNumber(String value) {
        this.taxRegistrationNumber = value;
    }

    /**
     * Gets the value of the reportingPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportingPeriod() {
        return reportingPeriod;
    }

    /**
     * Sets the value of the reportingPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportingPeriod(String value) {
        this.reportingPeriod = value;
    }

    /**
     * Gets the value of the taxTrackedOnPurchases property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTaxTrackedOnPurchases() {
        return taxTrackedOnPurchases;
    }

    /**
     * Sets the value of the taxTrackedOnPurchases property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTaxTrackedOnPurchases(Boolean value) {
        this.taxTrackedOnPurchases = value;
    }

    /**
     * Gets the value of the taxOnPurchasesAccountRef property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceType }
     *     
     */
    public ReferenceType getTaxOnPurchasesAccountRef() {
        return taxOnPurchasesAccountRef;
    }

    /**
     * Sets the value of the taxOnPurchasesAccountRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceType }
     *     
     */
    public void setTaxOnPurchasesAccountRef(ReferenceType value) {
        this.taxOnPurchasesAccountRef = value;
    }

    /**
     * Gets the value of the taxTrackedOnSales property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTaxTrackedOnSales() {
        return taxTrackedOnSales;
    }

    /**
     * Sets the value of the taxTrackedOnSales property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTaxTrackedOnSales(Boolean value) {
        this.taxTrackedOnSales = value;
    }

    /**
     * Gets the value of the taxTrackedOnSalesAccountRef property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceType }
     *     
     */
    public ReferenceType getTaxTrackedOnSalesAccountRef() {
        return taxTrackedOnSalesAccountRef;
    }

    /**
     * Sets the value of the taxTrackedOnSalesAccountRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceType }
     *     
     */
    public void setTaxTrackedOnSalesAccountRef(ReferenceType value) {
        this.taxTrackedOnSalesAccountRef = value;
    }

    /**
     * Gets the value of the taxOnTax property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTaxOnTax() {
        return taxOnTax;
    }

    /**
     * Sets the value of the taxOnTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTaxOnTax(Boolean value) {
        this.taxOnTax = value;
    }

    /**
     * Gets the value of the lastFileDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getLastFileDate() {
        return lastFileDate;
    }

    /**
     * Sets the value of the lastFileDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastFileDate(Date value) {
        this.lastFileDate = value;
    }

    /**
     * Gets the value of the taxAgencyExt property.
     * 
     * @return
     *     possible object is
     *     {@link IntuitAnyType }
     *     
     */
    public IntuitAnyType getTaxAgencyExt() {
        return taxAgencyExt;
    }

    /**
     * Sets the value of the taxAgencyExt property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntuitAnyType }
     *     
     */
    public void setTaxAgencyExt(IntuitAnyType value) {
        this.taxAgencyExt = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof TaxAgency)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final TaxAgency that = ((TaxAgency) object);
        {
            ReferenceType lhsSalesTaxCodeRef;
            lhsSalesTaxCodeRef = this.getSalesTaxCodeRef();
            ReferenceType rhsSalesTaxCodeRef;
            rhsSalesTaxCodeRef = that.getSalesTaxCodeRef();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "salesTaxCodeRef", lhsSalesTaxCodeRef), LocatorUtils.property(thatLocator, "salesTaxCodeRef", rhsSalesTaxCodeRef), lhsSalesTaxCodeRef, rhsSalesTaxCodeRef)) {
                return false;
            }
        }
        {
            String lhsSalesTaxCountry;
            lhsSalesTaxCountry = this.getSalesTaxCountry();
            String rhsSalesTaxCountry;
            rhsSalesTaxCountry = that.getSalesTaxCountry();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "salesTaxCountry", lhsSalesTaxCountry), LocatorUtils.property(thatLocator, "salesTaxCountry", rhsSalesTaxCountry), lhsSalesTaxCountry, rhsSalesTaxCountry)) {
                return false;
            }
        }
        {
            ReferenceType lhsSalesTaxReturnRef;
            lhsSalesTaxReturnRef = this.getSalesTaxReturnRef();
            ReferenceType rhsSalesTaxReturnRef;
            rhsSalesTaxReturnRef = that.getSalesTaxReturnRef();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "salesTaxReturnRef", lhsSalesTaxReturnRef), LocatorUtils.property(thatLocator, "salesTaxReturnRef", rhsSalesTaxReturnRef), lhsSalesTaxReturnRef, rhsSalesTaxReturnRef)) {
                return false;
            }
        }
        {
            String lhsTaxRegistrationNumber;
            lhsTaxRegistrationNumber = this.getTaxRegistrationNumber();
            String rhsTaxRegistrationNumber;
            rhsTaxRegistrationNumber = that.getTaxRegistrationNumber();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "taxRegistrationNumber", lhsTaxRegistrationNumber), LocatorUtils.property(thatLocator, "taxRegistrationNumber", rhsTaxRegistrationNumber), lhsTaxRegistrationNumber, rhsTaxRegistrationNumber)) {
                return false;
            }
        }
        {
            String lhsReportingPeriod;
            lhsReportingPeriod = this.getReportingPeriod();
            String rhsReportingPeriod;
            rhsReportingPeriod = that.getReportingPeriod();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "reportingPeriod", lhsReportingPeriod), LocatorUtils.property(thatLocator, "reportingPeriod", rhsReportingPeriod), lhsReportingPeriod, rhsReportingPeriod)) {
                return false;
            }
        }
        {
            Boolean lhsTaxTrackedOnPurchases;
            lhsTaxTrackedOnPurchases = this.isTaxTrackedOnPurchases();
            Boolean rhsTaxTrackedOnPurchases;
            rhsTaxTrackedOnPurchases = that.isTaxTrackedOnPurchases();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "taxTrackedOnPurchases", lhsTaxTrackedOnPurchases), LocatorUtils.property(thatLocator, "taxTrackedOnPurchases", rhsTaxTrackedOnPurchases), lhsTaxTrackedOnPurchases, rhsTaxTrackedOnPurchases)) {
                return false;
            }
        }
        {
            ReferenceType lhsTaxOnPurchasesAccountRef;
            lhsTaxOnPurchasesAccountRef = this.getTaxOnPurchasesAccountRef();
            ReferenceType rhsTaxOnPurchasesAccountRef;
            rhsTaxOnPurchasesAccountRef = that.getTaxOnPurchasesAccountRef();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "taxOnPurchasesAccountRef", lhsTaxOnPurchasesAccountRef), LocatorUtils.property(thatLocator, "taxOnPurchasesAccountRef", rhsTaxOnPurchasesAccountRef), lhsTaxOnPurchasesAccountRef, rhsTaxOnPurchasesAccountRef)) {
                return false;
            }
        }
        {
            Boolean lhsTaxTrackedOnSales;
            lhsTaxTrackedOnSales = this.isTaxTrackedOnSales();
            Boolean rhsTaxTrackedOnSales;
            rhsTaxTrackedOnSales = that.isTaxTrackedOnSales();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "taxTrackedOnSales", lhsTaxTrackedOnSales), LocatorUtils.property(thatLocator, "taxTrackedOnSales", rhsTaxTrackedOnSales), lhsTaxTrackedOnSales, rhsTaxTrackedOnSales)) {
                return false;
            }
        }
        {
            ReferenceType lhsTaxTrackedOnSalesAccountRef;
            lhsTaxTrackedOnSalesAccountRef = this.getTaxTrackedOnSalesAccountRef();
            ReferenceType rhsTaxTrackedOnSalesAccountRef;
            rhsTaxTrackedOnSalesAccountRef = that.getTaxTrackedOnSalesAccountRef();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "taxTrackedOnSalesAccountRef", lhsTaxTrackedOnSalesAccountRef), LocatorUtils.property(thatLocator, "taxTrackedOnSalesAccountRef", rhsTaxTrackedOnSalesAccountRef), lhsTaxTrackedOnSalesAccountRef, rhsTaxTrackedOnSalesAccountRef)) {
                return false;
            }
        }
        {
            Boolean lhsTaxOnTax;
            lhsTaxOnTax = this.isTaxOnTax();
            Boolean rhsTaxOnTax;
            rhsTaxOnTax = that.isTaxOnTax();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "taxOnTax", lhsTaxOnTax), LocatorUtils.property(thatLocator, "taxOnTax", rhsTaxOnTax), lhsTaxOnTax, rhsTaxOnTax)) {
                return false;
            }
        }
        {
            Date lhsLastFileDate;
            lhsLastFileDate = this.getLastFileDate();
            Date rhsLastFileDate;
            rhsLastFileDate = that.getLastFileDate();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "lastFileDate", lhsLastFileDate), LocatorUtils.property(thatLocator, "lastFileDate", rhsLastFileDate), lhsLastFileDate, rhsLastFileDate)) {
                return false;
            }
        }
        {
            IntuitAnyType lhsTaxAgencyExt;
            lhsTaxAgencyExt = this.getTaxAgencyExt();
            IntuitAnyType rhsTaxAgencyExt;
            rhsTaxAgencyExt = that.getTaxAgencyExt();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "taxAgencyExt", lhsTaxAgencyExt), LocatorUtils.property(thatLocator, "taxAgencyExt", rhsTaxAgencyExt), lhsTaxAgencyExt, rhsTaxAgencyExt)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            ReferenceType theSalesTaxCodeRef;
            theSalesTaxCodeRef = this.getSalesTaxCodeRef();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "salesTaxCodeRef", theSalesTaxCodeRef), currentHashCode, theSalesTaxCodeRef);
        }
        {
            String theSalesTaxCountry;
            theSalesTaxCountry = this.getSalesTaxCountry();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "salesTaxCountry", theSalesTaxCountry), currentHashCode, theSalesTaxCountry);
        }
        {
            ReferenceType theSalesTaxReturnRef;
            theSalesTaxReturnRef = this.getSalesTaxReturnRef();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "salesTaxReturnRef", theSalesTaxReturnRef), currentHashCode, theSalesTaxReturnRef);
        }
        {
            String theTaxRegistrationNumber;
            theTaxRegistrationNumber = this.getTaxRegistrationNumber();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "taxRegistrationNumber", theTaxRegistrationNumber), currentHashCode, theTaxRegistrationNumber);
        }
        {
            String theReportingPeriod;
            theReportingPeriod = this.getReportingPeriod();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "reportingPeriod", theReportingPeriod), currentHashCode, theReportingPeriod);
        }
        {
            Boolean theTaxTrackedOnPurchases;
            theTaxTrackedOnPurchases = this.isTaxTrackedOnPurchases();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "taxTrackedOnPurchases", theTaxTrackedOnPurchases), currentHashCode, theTaxTrackedOnPurchases);
        }
        {
            ReferenceType theTaxOnPurchasesAccountRef;
            theTaxOnPurchasesAccountRef = this.getTaxOnPurchasesAccountRef();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "taxOnPurchasesAccountRef", theTaxOnPurchasesAccountRef), currentHashCode, theTaxOnPurchasesAccountRef);
        }
        {
            Boolean theTaxTrackedOnSales;
            theTaxTrackedOnSales = this.isTaxTrackedOnSales();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "taxTrackedOnSales", theTaxTrackedOnSales), currentHashCode, theTaxTrackedOnSales);
        }
        {
            ReferenceType theTaxTrackedOnSalesAccountRef;
            theTaxTrackedOnSalesAccountRef = this.getTaxTrackedOnSalesAccountRef();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "taxTrackedOnSalesAccountRef", theTaxTrackedOnSalesAccountRef), currentHashCode, theTaxTrackedOnSalesAccountRef);
        }
        {
            Boolean theTaxOnTax;
            theTaxOnTax = this.isTaxOnTax();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "taxOnTax", theTaxOnTax), currentHashCode, theTaxOnTax);
        }
        {
            Date theLastFileDate;
            theLastFileDate = this.getLastFileDate();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "lastFileDate", theLastFileDate), currentHashCode, theLastFileDate);
        }
        {
            IntuitAnyType theTaxAgencyExt;
            theTaxAgencyExt = this.getTaxAgencyExt();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "taxAgencyExt", theTaxAgencyExt), currentHashCode, theTaxAgencyExt);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
