//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.18 at 04:20:25 PM IST 
//


package com.intuit.ipp.data;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UOMFeatureTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="UOMFeatureTypeEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Disabled"/&gt;
 *     &lt;enumeration value="SinglePerItem"/&gt;
 *     &lt;enumeration value="MultiplePerItem"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "UOMFeatureTypeEnum")
@XmlEnum
public enum UOMFeatureTypeEnum {

    @XmlEnumValue("Disabled")
    DISABLED("Disabled"),
    @XmlEnumValue("SinglePerItem")
    SINGLE_PER_ITEM("SinglePerItem"),
    @XmlEnumValue("MultiplePerItem")
    MULTIPLE_PER_ITEM("MultiplePerItem");
    private final String value;

    UOMFeatureTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static UOMFeatureTypeEnum fromValue(String v) {
        for (UOMFeatureTypeEnum c: UOMFeatureTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
